name: Spark Apps build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew -x test clean build
    - name: Test with Gradle
      run: ./gradlew test
    - name: Archive build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build/
    - name: Archive spark1 build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: spark1_build
        path: spark1/build/
    - name: Archive spark2 build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: spark2_build
        path: spark2/build/
    - name: Archive distribution artifacts
      uses: actions/upload-artifact@v1
      with:
        name: distribution
        path: build/distributions/
